version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell

linters-settings:
  govet:
    enable:
      - shadow

issues:
  exclude-dirs:
    - .gomodcache
    - .gomodcache-local
    - .gomodcache-docker
    - .gocache
